### ISSUE TITLE
Can not download to read

### ISSUE THREAD

**Issue by Gohan** [NapCat-App/Support#40] opened 2014-05-22 12:02 UTC

**Comment by zetachang** [comment] 2014-05-22 15:35
This is a bug caused by Github api change, we are preparing the next update. Sorry for the inconvenience. :sweat:

**Comment by zetachang** [comment] 2014-09-20 16:11
Finally, it has arrived App Store. Please download or upgrade to the latest version (1.4.0). It should be fixed.

Download link: https://itunes.apple.com/us/app/napcat-github-client-for-open/id606238223?mt=8

**Closed as completed by zetachang** 2014-09-20 16:11 UTC
