### ISSUE TITLE
Unable to save repo for reading

### ISSUE THREAD

**Issue by rgoulter** [NapCat-App/Support#38] opened 2014-04-19 05:07 UTC
Consistently given "error, try again later".

**Comment by zetachang** [comment] 2014-04-19 07:36
Hi, 

Thanks for reporting this. I am looking into the issue and will get back to you soon.

Sorry for the inconvenience. :sweat:

**Comment by zetachang** [comment] 2014-04-20 14:16
Hi,

I've discovered that the issue is caused by the changing api format from github. It has beed fixed and will be delivered in the next update. Really appreciate your waiting :smiley_cat:

**Comment by zetachang** [comment] 2014-09-20 16:13
Finally, it has arrived App Store. Please download or upgrade to the latest version (1.4.0). It should be fixed.

Download link: https://itunes.apple.com/us/app/napcat-github-client-for-open/id606238223?mt=8

**Closed as completed by zetachang** 2014-09-20 16:13 UTC

**Comment by rgoulter** [comment] 2014-09-21 01:18
Yup, got the latest version and it works. :-) Thanks.
